import { Job } from "../types";

export const JOBS_LIST: Job[] = [
  {
    id: "firefighter",
    title: "소방관",
    emoji: "👨‍🚒",
    color: "bg-red-500",
    accentColor: "#EF4444",
    topCap: "방화복 자켓",
    topDesc: "빨간 영웅 소방모, 무전기 가젯",
    bottomCap: "열차단 방화바지",
    bottomDesc: "든든한 검정 안전 장화",
    description: "용감하게 이웃을 돕고 위험한 불을 꺼주는 영웅",
    topId: "firefighter"
  },
  {
    id: "police",
    title: "경찰관",
    emoji: "👮",
    color: "bg-blue-600",
    accentColor: "#2563EB",
    topCap: "경찰관 제복 제비자켓",
    topDesc: "자랑스러운 경찰 일자모, 반짝이는 별 단추",
    bottomCap: "무릎단정 경찰 제복바지",
    bottomDesc: "검정색 경찰 단화구두",
    description: "동네의 평화와 규칙을 위해 나서는 용감한 수호자",
    topId: "police"
  },
  {
    id: "doctor",
    title: "의사",
    emoji: "🩺",
    color: "bg-teal-500",
    accentColor: "#14B8A6",
    topCap: "순백의 가운 & 청진기",
    topDesc: "치료 반사경 헤드밴드",
    bottomCap: "수술방 에메랄드 스크럽스 바지",
    bottomDesc: "편안한 화이트 고무 크로그",
    description: "아픈 이웃을 사랑하는 마음으로 정성껏 치료하는 사람",
    topId: "doctor"
  },
  {
    id: "nurse",
    title: "간호사",
    emoji: "👩‍⚕️",
    color: "bg-rose-400",
    accentColor: "#F43F5E",
    topCap: "사랑이 넘치는 핑크 유니폼",
    topDesc: "천사표 간호사 하트 캡",
    bottomCap: "핑크색 활동 유니폼 바지",
    bottomDesc: "달리기도 거뜬한 하얀색 간호 스니커즈",
    description: "아픈 사람의 마음과 몸을 친절하고 세심하게 보듬는 따뜻한 보석",
    topId: "nurse"
  },
  {
    id: "baker",
    title: "제빵사",
    emoji: "👨‍🍳",
    color: "bg-amber-500",
    accentColor: "#F59E0B",
    topCap: "화이트 셰프 카라 옷",
    topDesc: "뽀송보송한 빨간 리본 셰프 왕모자",
    bottomCap: "체크무늬 주방바지",
    bottomDesc: "뜨거운 오븐도 안전한 빵장갑 & 제빵화",
    description: "맛있는 밀가루로 매콤달콤 고소한 빵과 케이크를 굽는 사람",
    topId: "baker"
  },
  {
    id: "zookeeper",
    title: "사육사",
    emoji: "🦁",
    color: "bg-emerald-600",
    accentColor: "#059669",
    topCap: "카키 주머니 탐험조끼",
    topDesc: "동물 발자국 카키 사파리 모자",
    bottomCap: "갈색 카고 탐험바지",
    bottomDesc: "동물들과 뛰어다닐 수 있는 등산용 가죽 장화",
    description: "귀여운 밀림의 동물 친구들의 건강과 밥을 챙겨주는 친근한 친구",
    topId: "zookeeper"
  },
  {
    id: "ballerina",
    title: "발레리나",
    emoji: "🩰",
    color: "bg-pink-400",
    accentColor: "#F472B6",
    topCap: "반짝이는 핑크 발레 코르셋 탑",
    topDesc: "공주님 실버 피나클 티아라 왕관",
    bottomCap: "몽실몽실 솜사탕 핑크 샤튜튜",
    bottomDesc: "우아하고 부드러운 분홍색 발레토 슈즈 & 리본끈",
    description: "우아한 몸짓과 화려한 턴으로 아름다운 음악을 표현하는 무용가",
    topId: "ballerina"
  },
  {
    id: "idol",
    title: "아이돌 스타",
    emoji: "🎤",
    color: "bg-violet-500",
    accentColor: "#8B5CF6",
    topCap: "글리터 스팽글 무대용 자켓",
    topDesc: "무대 고성능 헤드 마이크 & 보라빛 별 헤어핀",
    bottomCap: "반짝이는 스팽글 댄스 하의",
    bottomDesc: "무대 레이저에도 번쩍이는 실버 글리터 플랫폼 부츠",
    description: "빛나는 무대 위에서 춤과 노래로 행복을 실어다 주는 만능 엔터테이너",
    topId: "idol"
  },
  {
    id: "skating",
    title: "피겨스케이터",
    emoji: "⛸️",
    color: "bg-sky-400",
    accentColor: "#38BDF8",
    topCap: "하늘하늘 은하수 레이스 탑",
    topDesc: "에메랄드빛 크리스탈 물망초 머리 장식",
    bottomCap: "은반의 눈꽃 셔링 미니스커트",
    bottomDesc: "얼음 위를 씽씽 달리는 화이트 은반 스케이트 구두",
    description: "하얀 얼음 위를 나비처럼 날아올라 우아하고 멋지게 연기하는 얼음 요정",
    topId: "skating"
  },
  {
    id: "mechanic",
    title: "정비공",
    emoji: "🔧",
    color: "bg-zinc-600",
    accentColor: "#52525B",
    topCap: "공구가 든 연장 주머니 오버롤 작업복",
    topDesc: "정비 전용 메카닉 야구캡, 공구 가이드 헤어",
    bottomCap: "튼튼하고 활동적인 데님 카고 작업바지",
    bottomDesc: "무거운 타이어도 끄떡없는 가죽 안전작업화",
    description: "고장 난 자동차나 우렁찬 기계를 척척 고쳐내는 소중한 팩토리 고수",
    topId: "mechanic"
  },
  {
    id: "astronaut",
    title: "우주비행사",
    emoji: "🚀",
    color: "bg-indigo-500",
    accentColor: "#6366F1",
    topCap: "은빛 하이테크 우주 조끼",
    topDesc: "홀로그램 우주 통신 헬멧, 블루 윈도우 마일드 고글",
    bottomCap: "빵빵한 공기압축 은하수 바지",
    bottomDesc: "무중력 달나라를 둥둥 오르는 화이트 우주 부츠",
    description: "넓고 신비한 은하수를 탐험하며 별과 행성의 비밀을 연구하는 개척자",
    topId: "astronaut"
  },
  {
    id: "pilot",
    title: "파일럿",
    emoji: "✈️",
    color: "bg-slate-700",
    accentColor: "#334155",
    topCap: "단정히 개어진 4줄 견장 가운",
    topDesc: "황금 날개 엠블럼 선장 캡, 세련된 반사 보잉 선글라스",
    bottomCap: "다리선이 칼같이 잡힌 네이비 오피서 바지",
    bottomDesc: "안전하게 비행기를 정렬시켜 줄 블랙 유니폼 구두",
    description: "구름을 뚫고 끝없는 하늘을 안전하게 운전하는 크루즈 기장님",
    topId: "pilot"
  },
  {
    id: "explorer",
    title: "탐험가",
    emoji: "🤠",
    color: "bg-orange-700",
    accentColor: "#C2410C",
    topCap: "카메라 끈 & 주머니 탐험조끼",
    topDesc: "나뭇잎 장식 정글 탐험 모자, 정찰 망원경",
    bottomCap: "사막용 가볍고 튼튼한 하프 팬츠",
    bottomDesc: "진흙 길도 비켜가는 가죽 레이스 모험 장화",
    description: "전설 속 고대 유적과 보물, 깊은 숲속을 정밀 탐험하는 용맹한 모험가",
    topId: "explorer"
  },
  {
    id: "magician",
    title: "마술사",
    emoji: "🎩",
    color: "bg-fuchsia-600",
    accentColor: "#C084FC",
    topCap: "크림슨 안감 턱시도 & 빨간 리본 나비타이",
    topDesc: "별빛 무늬 검정 마술 실크 햇 (비둘기 장식)",
    bottomCap: "은빛 핀스트라이프 연주 신사복 바지",
    bottomDesc: "공중부양도 가능한 반짝반짝 에나멜 마술사 정장구두",
    description: "신기하고 우아한 손놀림으로 놀라운 요술과 웃음을 전해주는 손기술 마술사",
    topId: "magician"
  },
  {
    id: "scientist",
    title: "과학자",
    emoji: "🧪",
    color: "bg-cyan-600",
    accentColor: "#0891B2",
    topCap: "바이오하자드 뱃지 실험용 스모크 코트",
    topDesc: "동그란 네온 옐로 실험 전용 보안경",
    bottomCap: "실험을 위한 무향 화이트 연구 정장바지",
    bottomDesc: "시약이 떨어져도 안전한 하얀 안전 정전기화",
    description: "신비한 플라스크 용액과 가루를 섞어 세상을 바꿀 발명품을 만드는 발명가",
    topId: "scientist"
  },
  {
    id: "farmer",
    title: "농부",
    emoji: "👩‍🌾",
    color: "bg-yellow-600",
    accentColor: "#CA8A04",
    topCap: "편안한 노란 체크무늬 가을남방",
    topDesc: "빨간 밴드 둥글둥글 밀짚 구멍 모자",
    bottomCap: "황금 해바라기가 그려진 청록색 귀여운 멜빵 pants",
    bottomDesc: "흙이 묻은 노랑 물 장화",
    description: "자연을 사랑하고 맛있는 곡물과 싱싱한 과일을 기르는 정직한 손길",
    topId: "farmer"
  },
  {
    id: "soccer",
    title: "축구선수",
    emoji: "⚽",
    color: "bg-red-600",
    accentColor: "#DC2626",
    topCap: "자랑스러운 대한민국 축구대표 호랑이 유니폼",
    topDesc: "선명한 형광색 네온 헤어 골대 밴드",
    bottomCap: "바람만큼 가벼운 검정 트레이닝 스포츠 쇼츠",
    bottomDesc: "잔디 위를 쌩쌩 접지해 주는 형광 축구 스파이커화",
    description: "운동장을 힘차게 달리며 화려한 골을 날리는 자랑스러운 월드 스타",
    topId: "soccer"
  },
  {
    id: "diver",
    title: "스쿠버다이버",
    emoji: "🤿",
    color: "bg-sky-600",
    accentColor: "#0284C7",
    topCap: "방수 산소통 검노 네오프렌 전신수트 상의",
    topDesc: "바다가 선명하게 보이는 스쿠버 수중 코안경 & 마우스 마일드 호스",
    bottomCap: "방수 지퍼 보조 포켓 수트 하의",
    bottomDesc: "물속을 가볍게 헤엄치는 바다 거북 노랑 오리발(Flippers)",
    description: "깊고 아름다운 심해 속 물고기를 만나고 바다를 청소하는 멋진 탐사대장",
    topId: "diver"
  },
  {
    id: "hairstylist",
    title: "미용사",
    emoji: "✂️",
    color: "bg-pink-500",
    accentColor: "#EC4899",
    topCap: "가위 수첩 앞치마 조끼자켓",
    topDesc: "알록달록 화려한 머리 롤 구슬 핀",
    bottomCap: "헤어 가루가 안 묻는 카고 린넨 바지",
    bottomDesc: "하루 종일 서 있어도 편안한 컬러블록 플랫폼 슈즈",
    description: "가위와 에어드라이어로 사람들의 지저분한 머리를 마법처럼 신나게 바꾸는 마술 헤어 디자이너",
    topId: "hairstylist"
  },
  {
    id: "gamedeveloper",
    title: "게임 개발자",
    emoji: "💻",
    color: "bg-purple-600",
    accentColor: "#7C3AED",
    topCap: "레트로 오락실 컨트롤러 프린트 후드 티",
    topDesc: "번쩍이는 RGB 라이트 하이테크 게이밍 헤드셋",
    bottomCap: "게이밍 모니터 불빛에 어울리는 네온라인 조거팬츠",
    bottomDesc: "홀로그램 보행등 스마트 하이탑 운동화",
    description: "동화 같은 상상 속 게임 세상을 컴퓨터 코딩으로 현실에 만들어 내는 마법사",
    topId: "gamedeveloper"
  },
  {
    id: "artist",
    title: "화가",
    emoji: "🎨",
    color: "bg-amber-400",
    accentColor: "#F59E0B",
    topCap: "물감이 묻은 아티스트 린넨 앞치마",
    topDesc: "낭만적인 프랑스식 빨간 베레모",
    bottomCap: "크레용 무늬 오가닉 면바지",
    bottomDesc: "편안하고 알록달록한 슬립온 단화",
    description: "하얀 캔버스 위에 형형색색의 상상력을 마법처럼 그려나가는 드로잉 거장",
    topId: "artist"
  },
  {
    id: "detective",
    title: "탐정",
    emoji: "🕵️",
    color: "bg-amber-800",
    accentColor: "#78350F",
    topCap: "브라운 체크 클래식 트렌치코트",
    topDesc: "사냥꾼 스타일 셜록홈즈 탐정모자",
    bottomCap: "단정한 신사 모직바지",
    bottomDesc: "발소리가 나지 않는 특수 비밀 탐정단화",
    description: "돋보기와 수첩을 들고 미스터리하고 흥미진진한 비밀 사건을 척척 해결하는 추리 천재",
    topId: "detective"
  },
  {
    id: "builder",
    title: "건축가",
    emoji: "👷",
    color: "bg-yellow-500",
    accentColor: "#EAB308",
    topCap: "초광각 반사선 황금 안전조끼",
    topDesc: "노란 고강도 엔지니어링 안전모",
    bottomCap: "튼튼하고 질긴 카고 건빵바지",
    bottomDesc: "못도 거뜬히 견디어 주는 가방식 강철안전화",
    description: "튼튼하고 아름다운 집과 학교, 놀이터를 안전하게 뚝딱 지어 올리는 공간의 마법사",
    topId: "builder"
  },
  {
    id: "gardener",
    title: "정원사",
    emoji: "🏡",
    color: "bg-emerald-500",
    accentColor: "#10B981",
    topCap: "잔디잎 장식 정원 데님 오버롤 조끼",
    topDesc: "포근하게 햇볕을 가려주는 둥근 밀짚모자",
    bottomCap: "흙 작업용 올리브 그린 바지",
    bottomDesc: "정원 연못 보수에 유용한 진흙용 갈색 장화",
    description: "파릇파릇한 식물들을 사랑하고 은은하고 아름다운 꽃과 나무 정원을 가꾸는 힐링 요정",
    topId: "gardener"
  },
  {
    id: "judge",
    title: "판사",
    emoji: "⚖️",
    color: "bg-slate-800",
    accentColor: "#1E293B",
    topCap: "단정하고 엄숙한 검정 법관 로브",
    topDesc: "클래식 화이트 스탠딩 칼라 카라보타이",
    bottomCap: "스마트 블랙 정장바지",
    bottomDesc: "자랑스러운 예복용 엘레강트 검정 가죽구두",
    description: "정의로운 법과 기준을 가지고 다투는 사람들을 평화롭고 지혜롭게 양보시키는 평화 지키미",
    topId: "judge"
  },
  {
    id: "lifeguard",
    title: "인명구조원",
    emoji: "🛟",
    color: "bg-rose-500",
    accentColor: "#F43F5E",
    topCap: "휘슬 장식 레드 수영대표 유니폼",
    topDesc: "해외해변 구명선 레드 장식모",
    bottomCap: "구조 대원용 퀵드라이 레드 숏팬츠",
    bottomDesc: "모래사장에서도 잘 달리는 미끄럼방지 구조샌들",
    description: "수영장과 파도치는 바다에서 이웃의 안전과 생명을 든든하게 지켜주는 수호천사",
    topId: "lifeguard"
  },
  {
    id: "musician",
    title: "음악가",
    emoji: "🎵",
    color: "bg-indigo-600",
    accentColor: "#4F46E5",
    topCap: "세련된 연주회용 블랙 턱시도 자켓",
    topDesc: "머리에 콕 얹는 알록달록 음표 헤어핀",
    bottomCap: "정결한 음악회 가죽 벨트 블랙팬츠",
    bottomDesc: "페달을 부드럽게 밟아주는 연주회용 소프트 단화",
    description: "피아노나 바이올린 등으로 마음을 울리는 아름다운 기적의 멜로디를 건네어주는 연주가",
    topId: "musician"
  },
  {
    id: "clown",
    title: "삐에로",
    emoji: "🤡",
    color: "bg-lime-500",
    accentColor: "#84CC16",
    topCap: "도트 무늬 둥글둥글 풍선 조끼",
    topDesc: "빨강 루돌프 코 & 풍성하고 알록달록 무지개 머리가발",
    bottomCap: "빨노파 무지개 서스펜더 멜빵 바지",
    bottomDesc: "우스꽝스럽고 거대한 오렌지색 삐에로 왕 구두",
    description: "서커스 무대에서 재미난 풍선 아트와 저글링으로 아이들에게 큰 웃음보따리를 선물하는 장난꾸러기",
    topId: "clown"
  },
  {
    id: "racer",
    title: "카레이서",
    emoji: "🏎️",
    color: "bg-neutral-800",
    accentColor: "#171717",
    topCap: "치밀하게 보강된 체크무늬 레이싱 자켓",
    topDesc: "시속 300도 거뜬한 풀페이스 특수 헬멧",
    bottomCap: "열 차단 멜빵 레이싱 바지",
    bottomDesc: "페달을 민첩하게 밟는 하이테크 레이싱 부츠",
    description: "서킷 위의 번개처럼 빠른 속도로 레이싱 카를 타고 트랙을 안전하게 돌며 1등 대장을 차지하는 영웅",
    topId: "racer"
  },
  {
    id: "vet",
    title: "수의사",
    emoji: "🐱",
    color: "bg-emerald-400",
    accentColor: "#34D399",
    topCap: "귀여운 강아지가 숨은 보들민트 치료자켓",
    topDesc: "반짝이는 스마트 고배율 헤드밴드 기기",
    bottomCap: "활동성이 우수한 카고형 올리브 검진바지",
    bottomDesc: "동물들이 좋아하는 꼬꼬마 발바닥 슬립온 슈즈",
    description: "아픈 강아지나 아기 고양이 등 소중한 동물 친구들을 따뜻한 마음으로 정성껏 고치는 닥터",
    topId: "vet"
  }
];
